#select mode 
# vqc :run vqc optimize step 
# debug : culcualte initial loss_func 今のところ
# test : test vqc circuit with optimized parameters 未実装
mode: "vqc"

# System configuration
nqubit: 7
# State options: 'dmatrix' and 'statevector' ここ分かってない
state: "dmatrix"

#VQC configuration
vqc:
  iteration: 5

  #Optimization configuration
  optimization:
    status: True
    algorithm: "SLSQP"
    constraint: False

  #circuit config
  ansatz:
    #'xy', 'ising', 'heisenberg' xyしか作ってない 
    type: "xy"
    depth: 12
    gateset: 1
    ugate:
      coefficient:
        cn: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        bn: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        r: 0
      time:
        type: "random"
        value: []
        min: 0.0
        max: 10.0
    noise:
      status: False
      value: []

    #'random' or List[float]
    init_param: "random"

  #dataset configuration
  Dataset:
    feature_num: 4
    encode_type: 1   #0: 最初の1層目の4パラメータにそのまま特徴量を入れる。汎用性なさすぎるので多分あまり使わないと思う 1: 0ビット目一つ目に特徴量、他はランダムなパラメータで特徴量分回路を繰り返すタイプ。多分こっちで進めるかも？ 2: 0の形の後ろに何そうかランダムな角度パラメータの回路を挟む
    train:
      path: "dataset/iris/iris_processed_train.data"
      num: 80
    test1:
      path: "dataset/iris/iris_processed_test1.data"
      num: 5
    test2:
      path: "dataset/iris/iris_processed_test2.data"
      num: 5


#DBに出すやつ
output:
  project:
    id: "honda-project"
  bigquery:
    import: False
    dataset: job_results
    table: vqc


